name: deploy

on:
  push:
    branches:
      - master
jobs:
  build:
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: working dir
        run: | 
          pwd   
          ls -la
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: test
        run: |
          pwd
          ls -la
          npm install
          npm test    