name: testing

on:
  push:
    branches:
      - master
jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: deploy
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'GitHub'
        id: hello
      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.